image:
  repository: krumware/baseline-vue-app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
imagePullSecrets:
  - name: docker-push-user
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "traefik"
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: vue.212.2.247.167.sslip.io
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - hosts:
        - vue.212.2.247.167.sslip.io
      secretName: vue-secret-tls
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
